import Link from 'next/link';
import { ReactNode } from 'react';

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html>
      <head>
        <title>Create Next.js 13 APP</title>
        <meta name='description' content='Generated by create next 13 app' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body>
        <header>
          <nav>
            <Link href={'/'}>Home</Link>
            <Link href={'/blog'}>Blog</Link>
          </nav>
        </header>
        <section>{children}</section>
        <footer>Footer</footer>
      </body>
    </html>
  );
};

export default RootLayout;
